In [5]:
import numpy as np
input_shape = (4, 5, 6)
print(*input_shape)

4 5 6


In [21]:
num_inputs = 2
input_shape = (3,2,2)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [22]:
print(x.shape,'\n',w.shape,'\n',b.shape)

(2, 3, 2, 2) 
 (12, 3) 
 (3,)


In [23]:
np.ones((4, 1), dtype = np.float64)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [24]:
x

array([[[[-0.1       , -0.07391304],
         [-0.04782609, -0.02173913]],

        [[ 0.00434783,  0.03043478],
         [ 0.05652174,  0.0826087 ]],

        [[ 0.10869565,  0.13478261],
         [ 0.16086957,  0.18695652]]],


       [[[ 0.21304348,  0.23913043],
         [ 0.26521739,  0.29130435]],

        [[ 0.3173913 ,  0.34347826],
         [ 0.36956522,  0.39565217]],

        [[ 0.42173913,  0.44782609],
         [ 0.47391304,  0.5       ]]]])

In [31]:
X = x.reshape((2, np.prod(input_shape)))
X

array([[-0.1       , -0.07391304, -0.04782609, -0.02173913,  0.00434783,
         0.03043478,  0.05652174,  0.0826087 ,  0.10869565,  0.13478261,
         0.16086957,  0.18695652],
       [ 0.21304348,  0.23913043,  0.26521739,  0.29130435,  0.3173913 ,
         0.34347826,  0.36956522,  0.39565217,  0.42173913,  0.44782609,
         0.47391304,  0.5       ]])

In [27]:
x.shape[0]

2

In [29]:
x.shape[1:]

(3, 2, 2)

In [33]:
X.reshape(x.shape) == x

array([[[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]]])

# random seed test

In [42]:
for i in range(3):
    np.random.seed(None)
    print(np.random.randn(4))

[-1.28495154  0.24006869  0.95947267 -1.43565494]
[-0.80357196 -0.74198272  0.42685873  0.36319518]
[-1.73081922 -1.23391987  0.34631494 -1.42882661]


In [37]:
np.random.seed(0)
for i in range(3):
    print(np.random.randn(4))

[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]


In [38]:
for i in range(3):
    print()
    np.random.seed(0)
    for j in range(3):
        print(np.random.randn(4))
        


[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]

[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]

[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]


In [52]:
[*range(3)]

[0, 1, 2]

In [62]:
for i in range(3):
    print(3-i)

3
2
1


In [1]:
[{"mode": "train"} for i in range(10)]

[{'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'}]