In [1]:
import numpy as np
input_shape = (4, 5, 6)
print(*input_shape)

4 5 6


In [3]:
num_inputs = 2
input_shape = (3,2,2)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [22]:
print(x.shape,'\n',w.shape,'\n',b.shape)

(2, 3, 2, 2) 
 (12, 3) 
 (3,)


In [23]:
np.ones((4, 1), dtype = np.float64)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [24]:
x

array([[[[-0.1       , -0.07391304],
         [-0.04782609, -0.02173913]],

        [[ 0.00434783,  0.03043478],
         [ 0.05652174,  0.0826087 ]],

        [[ 0.10869565,  0.13478261],
         [ 0.16086957,  0.18695652]]],


       [[[ 0.21304348,  0.23913043],
         [ 0.26521739,  0.29130435]],

        [[ 0.3173913 ,  0.34347826],
         [ 0.36956522,  0.39565217]],

        [[ 0.42173913,  0.44782609],
         [ 0.47391304,  0.5       ]]]])

In [31]:
X = x.reshape((2, np.prod(input_shape)))
X

array([[-0.1       , -0.07391304, -0.04782609, -0.02173913,  0.00434783,
         0.03043478,  0.05652174,  0.0826087 ,  0.10869565,  0.13478261,
         0.16086957,  0.18695652],
       [ 0.21304348,  0.23913043,  0.26521739,  0.29130435,  0.3173913 ,
         0.34347826,  0.36956522,  0.39565217,  0.42173913,  0.44782609,
         0.47391304,  0.5       ]])

In [27]:
x.shape[0]

2

In [29]:
x.shape[1:]

(3, 2, 2)

In [33]:
X.reshape(x.shape) == x

array([[[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]],


       [[[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True]]]])

# random seed test

In [42]:
for i in range(3):
    np.random.seed(None)
    print(np.random.randn(4))

[-1.28495154  0.24006869  0.95947267 -1.43565494]
[-0.80357196 -0.74198272  0.42685873  0.36319518]
[-1.73081922 -1.23391987  0.34631494 -1.42882661]


In [37]:
np.random.seed(0)
for i in range(3):
    print(np.random.randn(4))

[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]


In [38]:
for i in range(3):
    print()
    np.random.seed(0)
    for j in range(3):
        print(np.random.randn(4))
        


[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]

[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]

[1.76405235 0.40015721 0.97873798 2.2408932 ]
[ 1.86755799 -0.97727788  0.95008842 -0.15135721]
[-0.10321885  0.4105985   0.14404357  1.45427351]


In [52]:
[*range(3)]

[0, 1, 2]

In [62]:
for i in range(3):
    print(3-i)

3
2
1


In [1]:
[{"mode": "train"} for i in range(10)]

[{'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'},
 {'mode': 'train'}]

In [6]:
x = np.random.randn(12).reshape(3,4)
x

array([[-0.63780316, -0.72036137, -0.07713793, -0.57156465],
       [ 0.37010098, -0.35400354,  1.76479047,  1.98653418],
       [-1.10128273, -0.37017281, -1.1634712 , -1.07554673]])

In [7]:

np.pad(x,((1,2),(1,3)),'constant',constant_values = (0,0))

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -0.63780316, -0.72036137, -0.07713793, -0.57156465,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.37010098, -0.35400354,  1.76479047,  1.98653418,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -1.10128273, -0.37017281, -1.1634712 , -1.07554673,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]])

In [8]:
x

array([[-0.63780316, -0.72036137, -0.07713793, -0.57156465],
       [ 0.37010098, -0.35400354,  1.76479047,  1.98653418],
       [-1.10128273, -0.37017281, -1.1634712 , -1.07554673]])

In [11]:
x[:,2:5]

array([[-0.07713793, -0.57156465],
       [ 1.76479047,  1.98653418],
       [-1.1634712 , -1.07554673]])

In [12]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
a = np.random.randint(10, 100, size=9)
a = a.reshape((3,3))
print(a)

m = np.argmax(a)
print(m)
r, c = divmod(m, a.shape[1])
print(r, c)

[[51 76 53]
 [30 81 88]
 [43 99 87]]
7
2 1


In [29]:
ap = a.copy()
ap[ap!=np.max(ap)] = 0
ap[ap==np.max(ap)] = 1
ap

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [28]:
(ap == np.max(ap))

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [33]:
input_dim=(3, 32, 32)
np.random.randn(1,input_dim[0]).shape

(1, 3)

# reshape 与 复原

In [45]:
x = np.random.randn(2,6,2)
x

array([[[-1.03281924,  0.04481214],
        [-0.39458872, -1.12506179],
        [-0.78031602,  0.96565691],
        [-1.50555851, -1.75003981],
        [-2.05422993,  0.63397139],
        [-1.03172712,  0.36514273]],

       [[-1.15472174, -1.61916292],
        [ 0.71854956, -0.53323036],
        [-2.3815559 ,  1.25294832],
        [ 2.0013185 , -1.13237917],
        [ 1.42120514, -1.8875318 ],
        [ 2.1783106 ,  0.1498353 ]]])

In [46]:
xp = x.reshape(2, 3, 2, 2)
xp

array([[[[-1.03281924,  0.04481214],
         [-0.39458872, -1.12506179]],

        [[-0.78031602,  0.96565691],
         [-1.50555851, -1.75003981]],

        [[-2.05422993,  0.63397139],
         [-1.03172712,  0.36514273]]],


       [[[-1.15472174, -1.61916292],
         [ 0.71854956, -0.53323036]],

        [[-2.3815559 ,  1.25294832],
         [ 2.0013185 , -1.13237917]],

        [[ 1.42120514, -1.8875318 ],
         [ 2.1783106 ,  0.1498353 ]]]])

In [48]:
xp.reshape(x.shape) == x

array([[[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]])

In [41]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [43]:
a.reshape((1,3,1))

array([[[1],
        [2],
        [3]]])